/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gaby
 */
public class Jeu extends javax.swing.JFrame {

    /**
     * Creates new form Jeu
     */
    public Jeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Debut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SelectionJeu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadio1J = new javax.swing.JRadioButton();
        jRadio2J = new javax.swing.JRadioButton();
        ButtonSelecNbJ = new javax.swing.JButton();
        Jeu2Joueurs = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButtonContinuer = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        Map = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Pion1J1 = new javax.swing.JLabel();
        Pion2J1 = new javax.swing.JLabel();
        Pion3J1 = new javax.swing.JLabel();
        Pion4J1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Pion1J2 = new javax.swing.JLabel();
        Pion2J2 = new javax.swing.JLabel();
        Pion3J2 = new javax.swing.JLabel();
        Pion4J2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        BtChat = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        NbTourJ1 = new javax.swing.JLabel();
        NbTourJ2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        NbTour = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        EtatManche = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        PiocheMonstre = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        PionMort1J1 = new javax.swing.JLabel();
        PionMort2J1 = new javax.swing.JLabel();
        PionMort3J1 = new javax.swing.JLabel();
        PionMort4J1 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        PionMort1J2 = new javax.swing.JLabel();
        PionMort2J2 = new javax.swing.JLabel();
        PionMort3J2 = new javax.swing.JLabel();
        PionMort4J2 = new javax.swing.JLabel();
        Jeu1Joueur = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonContinuer1J = new javax.swing.JButton();
        jButtonRetour1J = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_finstere.gif"))); // NOI18N

        jButton1.setText("Commencer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DebutLayout = new javax.swing.GroupLayout(Debut);
        Debut.setLayout(DebutLayout);
        DebutLayout.setHorizontalGroup(
            DebutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DebutLayout.createSequentialGroup()
                .addGroup(DebutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DebutLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(DebutLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)))
                .addContainerGap(1136, Short.MAX_VALUE))
        );
        DebutLayout.setVerticalGroup(
            DebutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DebutLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jLabel2.setText("Selection du type de jeu");

        jRadio1J.setText("Un joueur");
        jRadio1J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio1JActionPerformed(evt);
            }
        });

        jRadio2J.setText("Deux joueurs");
        jRadio2J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio2JActionPerformed(evt);
            }
        });

        ButtonSelecNbJ.setText("Sélection");
        ButtonSelecNbJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSelecNbJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadio2J)
                            .addComponent(jRadio1J)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(ButtonSelecNbJ)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jRadio1J)
                .addGap(18, 18, 18)
                .addComponent(jRadio2J)
                .addGap(26, 26, 26)
                .addComponent(ButtonSelecNbJ)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SelectionJeuLayout = new javax.swing.GroupLayout(SelectionJeu);
        SelectionJeu.setLayout(SelectionJeuLayout);
        SelectionJeuLayout.setHorizontalGroup(
            SelectionJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SelectionJeuLayout.setVerticalGroup(
            SelectionJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setText("Paramètres");

        jLabel7.setText("Nom joueur 1");

        jLabel8.setText("Nom joueur 2");

        jTextField1.setText("NomJ2");

        jTextField2.setText("NomJ1");

        jButtonContinuer.setText("Continuer");
        jButtonContinuer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuerActionPerformed(evt);
            }
        });

        jButtonRetour.setText("Retour");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2))
                    .addComponent(jButtonRetour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonContinuer)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1)))
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContinuer)
                    .addComponent(jButtonRetour))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Jeu2JoueursLayout = new javax.swing.GroupLayout(Jeu2Joueurs);
        Jeu2Joueurs.setLayout(Jeu2JoueursLayout);
        Jeu2JoueursLayout.setHorizontalGroup(
            Jeu2JoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jeu2JoueursLayout.setVerticalGroup(
            Jeu2JoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fns_plateau.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finstere_flure.jpg"))); // NOI18N

        jLabel11.setText("Pions Joueur 1 :");

        Pion1J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pionblue_1_6_clair.gif"))); // NOI18N

        Pion2J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pionblue_3_4_clair.gif"))); // NOI18N

        Pion3J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pionblue_4_3_clair.gif"))); // NOI18N

        Pion4J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pionblue_5_2_clair.gif"))); // NOI18N

        jLabel16.setText("Nombre tour :");

        jLabel17.setText("Pions Joueur 2 : ");

        Pion1J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piongreen_1_6_clair.gif"))); // NOI18N

        Pion2J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piongreen_3_4_clair.gif"))); // NOI18N

        Pion3J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piongreen_4_3_clair.gif"))); // NOI18N

        Pion4J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piongreen_5_2_clair.gif"))); // NOI18N

        jLabel22.setText("Nombre tour :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField4.setText("jTextField4");

        BtChat.setText("Envoyer");

        jLabel23.setText("Chat :");

        NbTourJ1.setText("jLabel24");

        NbTourJ2.setText("jLabel25");

        jLabel26.setText("Nombre de tour(s) :");

        NbTour.setText("jLabel27");

        jLabel28.setText("Etat de la manche :");

        EtatManche.setText("jLabel29");

        jLabel30.setText("Information monstre :");

        jLabel31.setText("Pioche :");

        PiocheMonstre.setText("jLabel32");

        jLabel33.setText("jLabel33");

        jLabel34.setText("jLabel34");

        jLabel35.setText("Liste des pions mort Joueur 1 : ");

        PionMort1J1.setText("jLabel36");

        PionMort2J1.setText("jLabel37");

        PionMort3J1.setText("jLabel38");

        PionMort4J1.setText("jLabel39");

        jLabel40.setText("Liste des pions mort Joueurs 2 :");

        PionMort1J2.setText("jLabel41");

        PionMort2J2.setText("jLabel42");

        PionMort3J2.setText("jLabel43");

        PionMort4J2.setText("jLabel44");

        javax.swing.GroupLayout MapLayout = new javax.swing.GroupLayout(Map);
        Map.setLayout(MapLayout);
        MapLayout.setHorizontalGroup(
            MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NbTour))
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EtatManche))
                    .addComponent(jLabel30)
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PiocheMonstre))
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34))
                    .addComponent(jLabel35)
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(PionMort1J1)
                        .addGap(18, 18, 18)
                        .addComponent(PionMort2J1)
                        .addGap(18, 18, 18)
                        .addComponent(PionMort3J1))
                    .addComponent(PionMort4J1)
                    .addComponent(jLabel40)
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(PionMort1J2)
                        .addGap(18, 18, 18)
                        .addComponent(PionMort2J2)
                        .addGap(18, 18, 18)
                        .addComponent(PionMort3J2))
                    .addComponent(PionMort4J2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Pion1J1)
                        .addGap(18, 18, 18)
                        .addComponent(Pion2J1)
                        .addGap(18, 18, 18)
                        .addComponent(Pion3J1)
                        .addGap(18, 18, 18)
                        .addComponent(Pion4J1))
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NbTourJ1))
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(Pion1J2)
                        .addGap(18, 18, 18)
                        .addComponent(Pion2J2)
                        .addGap(18, 18, 18)
                        .addComponent(Pion3J2)
                        .addGap(18, 18, 18)
                        .addComponent(Pion4J2))
                    .addGroup(MapLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NbTourJ2))
                    .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtChat)
                        .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))))
                .addGap(92, 92, 92))
        );
        MapLayout.setVerticalGroup(
            MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MapLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pion1J1)
                    .addComponent(Pion2J1)
                    .addComponent(Pion3J1)
                    .addComponent(Pion4J1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(NbTourJ1))
                .addGap(18, 18, 18)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Pion1J2)
                    .addComponent(Pion2J2)
                    .addComponent(Pion3J2)
                    .addComponent(Pion4J2))
                .addGap(18, 18, 18)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(NbTourJ2))
                .addGap(87, 87, 87)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BtChat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MapLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(NbTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(EtatManche))
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(PiocheMonstre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(45, 45, 45)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PionMort1J1)
                    .addComponent(PionMort2J1)
                    .addComponent(PionMort3J1))
                .addGap(18, 18, 18)
                .addComponent(PionMort4J1)
                .addGap(31, 31, 31)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addGroup(MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PionMort1J2)
                    .addComponent(PionMort2J2)
                    .addComponent(PionMort3J2))
                .addGap(18, 18, 18)
                .addComponent(PionMort4J2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setText("Paramètre");

        jButtonContinuer1J.setText("Continuer");

        jButtonRetour1J.setText("Retour");

        jLabel4.setText("Nom Joueur :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jButtonRetour1J)
                .addGap(54, 54, 54)
                .addComponent(jButtonContinuer1J)
                .addGap(52, 52, 52))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContinuer1J)
                    .addComponent(jButtonRetour1J))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout Jeu1JoueurLayout = new javax.swing.GroupLayout(Jeu1Joueur);
        Jeu1Joueur.setLayout(Jeu1JoueurLayout);
        Jeu1JoueurLayout.setHorizontalGroup(
            Jeu1JoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jeu1JoueurLayout.setVerticalGroup(
            Jeu1JoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Debut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SelectionJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jeu2Joueurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jeu1Joueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Debut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SelectionJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jeu2Joueurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Jeu1Joueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.Debut.setVisible(true);
        this.SelectionJeu.setVisible(false);
        
        this.Debut.setVisible(false);
        this.SelectionJeu.setVisible(true);
        this.jPanel4.setVisible(false);
        this.Jeu2Joueurs.setVisible(false);
        this.Map.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonSelecNbJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSelecNbJActionPerformed
        // TODO add your handling code here:
        
        this.Debut.setVisible(false);
        this.SelectionJeu.setVisible(false);
        if(jRadio1J.isSelected()){
            this.Debut.setVisible(false);
            this.jPanel4.setVisible(true);
            this.Jeu2Joueurs.setVisible(false);
            this.SelectionJeu.setVisible(false);
            this.Map.setVisible(false);
        }if(jRadio2J.isSelected()){
            this.Debut.setVisible(false);
            this.jPanel4.setVisible(false);
            this.Jeu2Joueurs.setVisible(true);
            this.SelectionJeu.setVisible(false);
            this.Map.setVisible(false);
        }else{
            this.Debut.setVisible(false);
            this.jPanel4.setVisible(false);
            this.Jeu2Joueurs.setVisible(false);
            this.Map.setVisible(false);
        }
        this.Map.setVisible(false);
        
    }//GEN-LAST:event_ButtonSelecNbJActionPerformed

    private void jRadio1JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio1JActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadio1JActionPerformed

    private void jRadio2JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio2JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio2JActionPerformed

    private void jButtonContinuerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuerActionPerformed
        // TODO add your handling code here:
        this.Debut.setVisible(false);
        this.SelectionJeu.setVisible(false);
        
        this.Debut.setVisible(false);
        this.SelectionJeu.setVisible(false);
        this.jPanel4.setVisible(false);
        this.Jeu2Joueurs.setVisible(false);
        this.Map.setVisible(true);
        
    }//GEN-LAST:event_jButtonContinuerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtChat;
    private javax.swing.JButton ButtonSelecNbJ;
    private javax.swing.JPanel Debut;
    private javax.swing.JLabel EtatManche;
    private javax.swing.JPanel Jeu1Joueur;
    private javax.swing.JPanel Jeu2Joueurs;
    private javax.swing.JPanel Map;
    private javax.swing.JLabel NbTour;
    private javax.swing.JLabel NbTourJ1;
    private javax.swing.JLabel NbTourJ2;
    private javax.swing.JLabel PiocheMonstre;
    private javax.swing.JLabel Pion1J1;
    private javax.swing.JLabel Pion1J2;
    private javax.swing.JLabel Pion2J1;
    private javax.swing.JLabel Pion2J2;
    private javax.swing.JLabel Pion3J1;
    private javax.swing.JLabel Pion3J2;
    private javax.swing.JLabel Pion4J1;
    private javax.swing.JLabel Pion4J2;
    private javax.swing.JLabel PionMort1J1;
    private javax.swing.JLabel PionMort1J2;
    private javax.swing.JLabel PionMort2J1;
    private javax.swing.JLabel PionMort2J2;
    private javax.swing.JLabel PionMort3J1;
    private javax.swing.JLabel PionMort3J2;
    private javax.swing.JLabel PionMort4J1;
    private javax.swing.JLabel PionMort4J2;
    private javax.swing.JPanel SelectionJeu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContinuer;
    private javax.swing.JButton jButtonContinuer1J;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonRetour1J;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadio1J;
    private javax.swing.JRadioButton jRadio2J;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
